version: '3.3'
services:
  dashboard:
    container_name: ethereum-dashboard
    build:
      context: ./dashboard
      cache_from:
        - ubuntu:16.04
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "3000:3000"
    environment:
      WS_SECRET: "88888"
    volumes:
      - "/Users/apple/Desktop/kube-ethereum/env:/env"
  node-1:
    container_name: ethereum-node-1
    build:
      context: ./node
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.2"
          memory: "50M"
      restart_policy:
        condition: on-failture
    ports:
      - "8547:8545"
      - "2002:2000"
    environment:
      INSTANCE_NAME: "node-1"
      WS_SECRET: "88888"
    volumes:
      - "/Users/apple/Desktop/kube-ethereum/env:/env"
    depends_on:
      - dashboard
  node-2:
    container_name: ethereum-node-2
    build:
      context: ./node
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.2"
          memory: "50M"
      restart_policy:
        condition: on-failture
    ports:
      - "8546:8545"
      - "2001:2000"
    environment:
      INSTANCE_NAME: "node-2"
      WS_SECRET: "88888"
    volumes:
      - "/Users/apple/Desktop/kube-ethereum/env:/env"
    depends_on:
      - dashboard
  monitor:
    container_name: ethereum-monitor
    build:
      context: ./monitor
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.2"
          memory: "50M"
      restart_policy:
        condition: on-failture
    volumes:
      - "/Users/apple/Desktop/kube-ethereum/env:/env"
    depends_on:
      - dashboard
      - node-1
      - node-2