kind: PersistentVolume
apiVersion: v1
metadata:
  name: nfs-pv
  namespace: kubereum
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    namespace: kubereum
    name: nfs-pvc
  storageClassName: slow
  nfs:
    path: /env
    server: 10.28.120.25