kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: node
  namespace: kubereum
  labels:
    app: node
spec:
  replicas: 2
  template:
    metadata:
      name: node
      labels:
        app: node
    spec:
      containers:
      - name: node
        image: cijie/kubereum-node:0.1.1
        env:
        - name: WS_SECRET
          value: '88888'
        ports:
          - name: rpc
            containerPort: 8545
          - name: enode
            containerPort: 2000
        volumeMounts:
        - mountPath: /eth-net-intelligence-api/kubereum/node/env
          name: nfs-volume
        resources:
          requests:
            memory: "2048Mi"
            cpu: "3"
          limits:
            memory: "2048Mi"
            cpu: "3"
      volumes:
      - name: nfs-volume
        persistentVolumeClaim:
          claimName: nfs-pvc