kind: Service
apiVersion: v1
metadata:
  name: netstat
  namespace: kubereum
  labels:
    app: netstat
spec:
  type: NodePort
  ports:
  - nodePort: 30001
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: netstat