kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: netstat
  namespace: kubereum
  labels:
    app: netstat
spec:
  replicas: 1
  template:
    metadata:
      name: netstat
      labels:
        app: netstat
    spec:
      containers:
      - name: netstat
        image: cijie/kubereum-netstat:0.1.0
        env:
        - name: WS_SECRET
          value: '88888'
        ports:
          - name: netstat
            containerPort: 3000
        volumeMounts:
        - mountPath: /eth-netstats/kubereum/netstat/env
          name: nfs-volume
      volumes:
      - name: nfs-volume
        persistentVolumeClaim:
          claimName: nfs-pvc