kind: Service
apiVersion: v1
metadata:
  name: node
  namespace: kubereum
  labels:
    app: node
spec:
  type: NodePort
  ports:
  - nodePort: 30012
    port: 8545
    protocol: TCP
    targetPort: 8545
  selector:
    app: node